#!/usr/bin/env python3
"""research/66 two-stage column census -- reproducible.

Stage 1 (CSV -> resolved): for every table, compares the raw CSV column list
(data/schema-manifest.json `columns`, generated by research/build-manifest.py)
against what `resolve.py`'s own `_display_columns(spec)` would expose for a
resolved row of that table (the declared `display_columns` override if
present, else the default: `searchable_columns` + the table's own FK source
columns). This stage needs no doctype walk at all -- it is pure manifest
metadata, identical for every row of a table regardless of which doctype
reached it. Denominator = full raw CSV column count (`len(spec["columns"])`,
which includes the table's own key column) -- this matches research/64's
counting convention: the resolver always renames the key column to "key" and
that rename is credited as one resolved column, not dropped, so numerator =
len(display_columns) + 1.

Stage 2 (resolved -> emitted): unchanged in method from research/65 -- for
every table x path, resolve a representative doctype, wrap every resolved
row in a dict subclass that records every column name a handoff builder
calls .get() on, and diff resolved columns against read columns. This run
ALSO wraps `_constraints_and_preflight_lines` (ddi.py:371), not just the four
per-format `_FORMAT_BUILDERS`, so the "Set Key" preflight line (emitted by a
function research/65 did not instrument) is credited correctly instead of
appearing as a stage-2 gap on every path.

Usage: python3 research/census_columns.py
Run from anywhere; paths below are relative to this file.
"""
from __future__ import annotations

import csv
import io
import json
import sys
from contextlib import redirect_stdout
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL_ROOT = REPO_ROOT / "skill" / "document-design-intelligence"
SCRIPTS_DIR = SKILL_ROOT / "scripts"
DATA_DIR = SKILL_ROOT / "data"

sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(SCRIPTS_DIR / "lib"))

import resolve  # noqa: E402
import ddi  # noqa: E402
import data as datalib  # noqa: E402

FORMATS = ("docx", "pptx", "pdf", "png")

# research/64 D-B's reconciliation numbers (raw-CSV-column denominator,
# key-inclusive numerator), for the eight tables it named as still dropping
# payload after v0.3. Used only to print an explicit match/mismatch check.
RESEARCH_64 = {
    "cv-regions": (2, 14),
    "doc-styles": (4, 15),
    "doc-reasoning": (6, 10),
    "typefaces": (8, 15),
    "palettes": (8, 20),
    "page-formats": (10, 21),
    "render-targets": (8, 14),
    "doctypes": (9, 11),
}


class TrackedRow(dict):
    """dict subclass that records every key .get() is called with, into a
    shared set owned by the census (one set per table)."""

    def __init__(self, data, sink):
        super().__init__(data)
        object.__setattr__(self, "_sink", sink)

    def get(self, key, default=""):
        self._sink.add(key)
        return dict.get(self, key, default)


def _resolved_json(doc_key):
    """Call resolve.py exactly as the CLI would (--doctype <key> --json),
    capturing stdout, so the JSON shape matches what a model would actually
    pipe into `ddi.py handoff`."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        code = resolve.main(["--doctype", doc_key, "--json", "--data-dir", str(DATA_DIR)])
    if code != 0:
        return None
    return json.loads(buf.getvalue())


def _all_doc_keys():
    manifest = datalib.load_manifest(DATA_DIR)
    tables = manifest["tables"]
    entry_name = datalib.entry_table_name(tables)
    key_column = tables[entry_name]["key_column"]
    problems = datalib.ProblemLog()
    rows = datalib.load_table_rows(DATA_DIR, tables[entry_name], problems, table_name=entry_name)
    return [r.get(key_column, "") for r in rows if r.get(key_column, "")], tables


def stage1_census(tables_spec):
    """table -> dict(denominator, numerator, resolved_columns (non-key),
    gap_columns (non-key columns absent from both display_columns and the
    key rename))."""
    out = {}
    for table_name, spec in tables_spec.items():
        raw_columns = spec.get("columns", [])
        key_column = spec.get("key_column")
        display_cols = resolve._display_columns(spec)  # non-key columns resolve.py exposes
        denom = len(raw_columns)
        numerator = len(display_cols) + 1  # +1 for the always-present key rename
        gap_columns = [c for c in raw_columns if c != key_column and c not in display_cols]
        out[table_name] = {
            "denominator": denom,
            "numerator": numerator,
            "resolved_columns": sorted(display_cols),
            "gap_columns": sorted(gap_columns),
        }
    return out


def stage2_census(tables_spec, doc_keys):
    """(table, fmt) -> dict(doc_key, resolved, emitted, gap) -- same method
    as research/65, plus _constraints_and_preflight_lines wrapped."""
    all_table_names = sorted(tables_spec.keys())

    representative = {}
    reached_by = {}
    for doc_key in doc_keys:
        payload = _resolved_json(doc_key)
        if payload is None or payload.get("status") != "resolved":
            continue
        for table_name, rows in payload.get("resolved", {}).items():
            if rows and table_name not in representative:
                representative[table_name] = payload
                reached_by[table_name] = doc_key

    unreachable = [t for t in all_table_names if t not in representative]

    results = {}
    for table_name in all_table_names:
        payload = representative.get(table_name)
        if payload is None:
            continue
        doc_key = reached_by[table_name]
        resolved_rows = payload["resolved"][table_name]
        resolved_columns = set()
        for row in resolved_rows:
            resolved_columns.update(k for k in row.keys() if k != "key")

        for fmt in FORMATS:
            sink = set()
            tracked_resolved = {}
            for tname, trows in payload["resolved"].items():
                this_sink = sink if tname == table_name else set()
                tracked_resolved[tname] = [TrackedRow(r, this_sink) for r in trows]
            builder = ddi._FORMAT_BUILDERS[fmt]
            builder(tracked_resolved)
            # research/65's blind spot: this shared function runs once per
            # format in _build_handoff_lines but was never instrumented, so
            # constraints."Set Key" showed as a false stage-2 gap on every path.
            ddi._constraints_and_preflight_lines(tracked_resolved, fmt)
            emitted = sink & resolved_columns
            gap = resolved_columns - sink
            results[(table_name, fmt)] = {
                "doc_key": doc_key,
                "resolved": sorted(resolved_columns),
                "emitted": sorted(emitted),
                "gap": sorted(gap),
            }
    return unreachable, results, all_table_names


def main():
    doc_keys, tables_spec = _all_doc_keys()
    all_table_names = sorted(tables_spec.keys())

    stage1 = stage1_census(tables_spec)
    unreachable, stage2, _ = stage2_census(tables_spec, doc_keys)

    print("=== STAGE 1: CSV columns -> resolved (resolve.py _display_columns) ===")
    print(f"{'table':<16}{'resolved':>9}{'of':>4}{'match64':>9}  gap columns (non-key, never resolved)")
    for table_name in all_table_names:
        s1 = stage1[table_name]
        r64 = RESEARCH_64.get(table_name)
        match = "n/a"
        if r64 is not None:
            match = "OK" if (s1["numerator"], s1["denominator"]) == r64 else "MISMATCH"
        print(f"{table_name:<16}{s1['numerator']:>9}{s1['denominator']:>4}{match:>9}  "
              f"{', '.join(s1['gap_columns'])}")

    print(f"\n{len(doc_keys)} doctypes total; {len(all_table_names) - len(unreachable)}/"
          f"{len(all_table_names)} tables reached by at least one doctype's FK walk "
          "(stage 2 needs a reachable row; stage 1 does not)")
    if unreachable:
        print(f"UNREACHABLE (resolve.py-level, not a handoff drop): {', '.join(unreachable)}")

    print("\n=== STAGE 2: resolved -> emitted (per path builder + constraints/preflight) ===")
    print(f"{'table':<16}{'path':<6}{'doc_key':<20}{'resolved':>9}{'emitted':>9}{'gap':>5}  gap columns")
    for table_name in all_table_names:
        if table_name in unreachable:
            continue
        for fmt in FORMATS:
            r = stage2[(table_name, fmt)]
            print(f"{table_name:<16}{fmt:<6}{r['doc_key']:<20}{len(r['resolved']):>9}"
                  f"{len(r['emitted']):>9}{len(r['gap']):>5}  {', '.join(r['gap'])}")

    print("\n--- machine-readable ---")
    print(json.dumps({
        "stage1": stage1,
        "stage2_unreachable_tables": unreachable,
        "stage2_results": {f"{t}|{f}": stage2[(t, f)] for (t, f) in stage2},
    }, indent=2))


if __name__ == "__main__":
    main()
