#!/usr/bin/env python3
"""Unit tests for lib/pdf.py — run with the system Python (stdlib only).

Fixture: tests/fixtures/sample.pdf, a real one-page PDF generated by local
headless Chromium (see fixtures/sample.html for the source and the command
used, both checked in for reproducibility). It contains two embedded
Type0/CIDFontType2 Arial subsets (confirmed via direct inspection to use
/FontFile2, i.e. embedded TrueType) and one small raster image placed at
100x100 CSS pixels via a nested `cm`/`Do` inside a `q`/`Q` block, with an
outer page-level `cm` (Chromium's device-pixel-to-point scale) applied
before it — this is the specific structure that makes the graphics-state
matrix stack in `_content_ctm_at_do` load-bearing rather than optional; see
that function's docstring in pdf.py.
"""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import pdf  # noqa: E402

FIXTURE = Path(__file__).parent / "fixtures" / "sample.pdf"


@unittest.skipUnless(FIXTURE.exists(), "sample.pdf fixture not present")
class TestPageCount(unittest.TestCase):
    def test_one_page(self):
        self.assertEqual(pdf.page_count(str(FIXTURE)), 1)


@unittest.skipUnless(FIXTURE.exists(), "sample.pdf fixture not present")
class TestPageBoxes(unittest.TestCase):
    def test_media_box_present_trim_bleed_absent(self):
        boxes = pdf.page_boxes(str(FIXTURE))
        self.assertEqual(len(boxes), 1)
        box = boxes[0]
        self.assertIsNotNone(box["MediaBox"])
        self.assertEqual(len(box["MediaBox"]), 4)
        # Chromium's plain print-to-pdf output has no print-production boxes
        # at all — confirmed in research/14-print-production-values.md §1.
        self.assertIsNone(box["TrimBox"])
        self.assertIsNone(box["BleedBox"])


@unittest.skipUnless(FIXTURE.exists(), "sample.pdf fixture not present")
class TestEmbeddedFonts(unittest.TestCase):
    def test_both_arial_subsets_report_embedded(self):
        fonts_found = pdf.embedded_fonts(str(FIXTURE))
        self.assertEqual(len(fonts_found), 2)
        for name, embedded in fonts_found:
            self.assertTrue(embedded, f"{name} should be embedded (FontFile2)")
            self.assertIn("Arial", name)


@unittest.skipUnless(FIXTURE.exists(), "sample.pdf fixture not present")
class TestRasterDpi(unittest.TestCase):
    def test_one_image_resolved_with_correct_matrix_composition(self):
        rows = pdf.raster_dpi(str(FIXTURE))
        self.assertEqual(len(rows), 1)
        obj_id, width_px, height_px, placed_width_pt, dpi = rows[0]
        self.assertEqual((width_px, height_px), (10, 10))
        # CSS asked for 100x100 *px* at 96 CSS-dpi == 75pt (100 * 72 / 96).
        # A parser that read only the innermost `cm` (312.5, ignoring the
        # outer page-scale `cm` of ~0.24) would report ~312.5pt instead —
        # this assertion is the regression test for that exact bug, found
        # and fixed empirically while building this module.
        self.assertIsNotNone(placed_width_pt)
        self.assertAlmostEqual(placed_width_pt, 75.0, delta=0.5)
        self.assertIsNotNone(dpi)
        # 10px over a 75pt (1.0417in) placement ~= 9.6 dpi — a deliberately
        # tiny fixture image stretched large, i.e. a real "this image is
        # far too low-resolution for its placed size" case.
        self.assertAlmostEqual(dpi, 9.6, delta=0.2)

    def test_unplaced_or_unresolvable_image_reports_none_not_a_guess(self):
        # Synthetic: an Image XObject that exists in the file but is never
        # invoked via Do from any page content stream.
        import re
        data = FIXTURE.read_bytes()
        objects = pdf._iter_objects(data)
        image_obj_nums = [
            n for n, (d, _s) in objects.items()
            if d is not None and re.search(rb"/Subtype\s*/Image\b", d)
        ]
        self.assertTrue(image_obj_nums)
        rows = pdf.raster_dpi(str(FIXTURE))
        resolved_ids = {r[0] for r in rows}
        # Every image actually placed via Do resolved to a non-None DPI —
        # confirms the "report None, don't guess" path is only taken for
        # genuinely unresolved placements, not silently for everything.
        for row in rows:
            if row[0] in resolved_ids:
                self.assertIsNotNone(row[4])


class TestNeverGuessesOnMalformedInput(unittest.TestCase):
    def test_empty_file_gives_empty_results_not_a_crash(self):
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            f.write(b"%PDF-1.4\n%%EOF")
            path = f.name
        try:
            self.assertEqual(pdf.embedded_fonts(path), [])
            self.assertEqual(pdf.raster_dpi(path), [])
            self.assertIsNone(pdf.page_count(path))
            self.assertEqual(pdf.page_boxes(path), [])
        finally:
            Path(path).unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()
